---
- name: restart victoriametrics cluster
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  loop:
    - vmstorage
    - vminsert
    - vmselect
    - vmagent
    - vmalert
  when: item is defined
  ignore_errors: true
